[package]
name = "pi-makerpower-gpio"
version = "0.1.0"
edition = "2021"
authors = ["Matt Gauger"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rppal = "0.15.0"
